language: node_js
node_js: 
  - "stable"
services:
  - mysql
cache:
  directories:
    - "node_modules"
env:
  global:
    - PORT=3000
    - HOST=localhost
    - USE_TEST_DB=true
    - COOKIE_JWT_EXP_DAYS=3
    - HTTP_ONLY_COOKIE=true
    - SIGNED_COOKIE=true
    - COOKIE_DOMAIN=localhost
    - JWT_COOKIE_PATH=/
    - SECURE_COOKIE=false
    - JWT_SECRET=gssuKYUn
    - COOKIE_SECRET=FBQ8iZ5cY6kCFgsg
    - IS_TRAVIS=true
  jobs:
    - NODE_ENV=test
before_install:
  - mysql -e 'CREATE DATABASE SOLAR_TEST;'
install:
  - npm install
script:
  - npm test
after_success: 
  - npm run coverage