language: node_js
node_js: 
  - "stable"
services:
  - mysql
cache:
  directories:
    - "node_modules"
before_install:
  - mysql -e 'CREATE DATABASE solar_test;'
install:
  - npm install
  - npm install codecov -g
script:
  - npm test
after_success:
  - codecov