USE SOLAR;

DROP TABLE IF EXISTS PURCHASE_REQUEST;
DROP TABLE IF EXISTS SELL_REQUEST;
DROP TABLE IF EXISTS INVESTMENT;
DROP TABLE IF EXISTS CONTRACT;
DROP TABLE IF EXISTS HOMEOWNER;
DROP TABLE IF EXISTS INVESTOR;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    id INT PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE INVESTOR (
    id INT PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE HOMEOWNER (
    id INT PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE CONTRACT (
    id INT PRIMARY KEY,
    user_id INT,
    sale_amount INT NOT NULL,
    length INT NOT NULL,
    monthly_payment INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE INVESTMENT (
    id INT PRIMARY KEY,
    contract_id INT,
    investor_id INT,
    percentage FLOAT,
    for_sale BOOL
);


CREATE TABLE PURCHASE_REQUEST (
    id INT PRIMARY KEY,
    amount INT NOT NULL,
    date_created DATETIME NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE SELL_REQUEST (
    id INT PRIMARY KEY,
    amount INT NOT NULL,
    date_created DATETIME NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);